import React from "react";
import * as Icons from "./react-icons"; 

export const TECH_MAP: Record<string, { label: string; icon: React.ElementType }> = {
  react: { label: "React", icon: Icons.ReactjsIcon },
  nextjs: { label: "Next.js", icon: Icons.NextJsIcon },
  typescript: { label: "TypeScript", icon: Icons.TypescriptIcon },
  javascript: { label: "JavaScript", icon: Icons.JavascriptIcon },
  nodejs: { label: "Node.js", icon: Icons.NodejsIcon },
  python: { label: "Python", icon: Icons.PythonIcon },
  java: { label: "Java", icon: Icons.JavaIcon },
  html: { label: "HTML5", icon: Icons.HtmlIcon },
  css: { label: "CSS3", icon: Icons.CssIcon },
  tailwind: { label: "Tailwind CSS", icon: Icons.TailwindCssIcon },
  shadcn: { label: "Shadcn UI", icon: Icons.ShadcnuiIcon },
  prisma: { label: "Prisma", icon: Icons.PrismaIcon },
  drizzle: { label: "Drizzle", icon: Icons.DrizzleIcon },
  mongodb: { label: "MongoDB", icon: Icons.MongodbIcon },
  postgresql: { label: "PostgreSQL", icon: Icons.PostgresqlIcon },
  mysql: { label: "MySQL", icon: Icons.MysqlIcon },
  docker: { label: "Docker", icon: Icons.DockerIcon },
  aws: { label: "AWS", icon: Icons.AwsIcon },
  firebase: { label: "Firebase", icon: Icons.FirebaseIcon },
  supabase: { label: "Supabase", icon: Icons.SupabaseIcon },
  redux: { label: "Redux", icon: Icons.ReduxIcon },
  reactquery: { label: "React Query", icon: Icons.ReactqueryIcon },
  graphql: { label: "GraphQL", icon: Icons.GraphqlIcon },
  nestjs: { label: "NestJS", icon: Icons.NestjsIcon },
  express: { label: "Express", icon: Icons.ExpressIcon },
  springboot: { label: "Spring Boot", icon: Icons.SpringBootIcon },
  django: { label: "Django", icon: Icons.DjangoIcon },
  angular: { label: "Angular", icon: Icons.AngularjsIcon },
  bootstrap: { label: "Bootstrap", icon: Icons.BootstrapIcon },
  blender: { label: "Blender", icon: Icons.BlenderIcon },
  illustrator: { label: "Illustrator", icon: Icons.AdobeillustratorIcon },
  photoshop: { label: "Photoshop", icon: Icons.AdobephotoshopIcon },
  aftereffects: { label: "After Effects", icon: Icons.AdobeaftereffectsIcon },
  premierepro: { label: "Premiere Pro", icon: Icons.AdobepremiereproIcon },
  reactnative: { label: "React Native", icon: Icons.ReactNativeIcon },
  kafka: { label: "Kafka", icon: Icons.ApachekafkaIcon },
  rabbitmq: { label: "RabbitMQ", icon: Icons.RabbitmqIcon },
  redis: { label: "Redis", icon: Icons.RedisIcon },
  mongoose: { label: "Mongoose", icon: Icons.MongooseIcon },
  jwt: { label: "JWT", icon: Icons.JsonwebtokensIcon },
  kubernetes:{label:"Kubernetes",icon:Icons.KubernetesIcon},
  golang: { label: "Go", icon: Icons.GolangIcon },
  rust: { label: "Rust", icon: Icons.RustIcon },
  git: { label: "Git", icon: Icons.GithubIcon },
  figma: { label: "Figma", icon: Icons.FigmaIcon },
  vite: { label: "Vite", icon: Icons.ViteIcon },
  sass: { label: "Sass", icon: Icons.SassIcon },
  markdown: { label: "Markdown", icon: Icons.MarkdownIcon },
  vercel:{label:"Vercel",icon:Icons.VercelIcon},
  gatsby:{label:"Gatsby",icon:Icons.GatsbyIcon},
  reacthookform:{label:"React Hook Form",icon:Icons.ReacthookformIcon},
  socketio:{label:"Socket.io",icon:Icons.SocketdotioIcon},
  query:{label:"React Query",icon:Icons.ReactqueryIcon},
  vitest:{label:"Vitest",icon:Icons.VitestIcon},
  cypress:{label:"Cypress",icon:Icons.CypressIcon},
  turborepo:{label:"Turborepo",icon:Icons.TurborepoIcon},
  nx:{label:"Nx",icon:Icons.NxIcon},
  nginx:{label:"Nginx",icon:Icons.NginxIcon},
  tauri:{label:"Tauri",icon:Icons.TauriIcon},
  eslint:{label:"ESLint",icon:Icons.EslintIcon},
  prettier:{label:"Prettier",icon:Icons.PrettierIcon},
  clerk:{label:"Clerk",icon:Icons.ClerkIcon},
  prometheus:{label:"Prometheus",icon:Icons.PrometheusIcon},
  cplusplus:{label:"C++",icon:Icons.CplusplusIcon},
  unity:{label:"Unity",icon:Icons.UnityIcon},
  googlesheets:{label:"Google Sheets",icon:Icons.GooglesheetsIcon},
  googledocs:{label:"Google Docs",icon:Icons.GoogledocsIcon},
  fastify:{label:"Fastify",icon:Icons.FastifyIcon},
  jenkins:{label:"Jenkins",icon:Icons.JenkinsIcon},
  heroku:{label:"Heroku",icon:Icons.HerokuIcon},
  netlify:{label:"Netlify",icon:Icons.NetlifyIcon},
  githubactions:{label:"GitHub Actions",icon:Icons.GithubactionsIcon},
  digitalocean:{label:"DigitalOcean",icon:Icons.DigitaloceanIcon},
  planetscale:{label:"Planetscale",icon:Icons.PlanetscaleIcon},
  pnpm:{label:"pnpm",icon:Icons.PnpmIcon},
  grafana:{label:"Grafana",icon:Icons.GrafanaIcon},
  npm:{label:"npm",icon:Icons.NpmIcon},
  yarn:{label:"yarn",icon:Icons.YarnIcon},
  deno:{label:"Deno",icon:Icons.DenoIcon},
  bun:{label:"Bun",icon:Icons.BunIcon},
  expo:{label:"Expo",icon:Icons.ExpoIcon},
  github:{label:"GitHub",icon:Icons.GithubIcon},
  gitlab:{label:"GitLab",icon:Icons.GitlabIcon},
  azure:{label:"Azure",icon:Icons.AzureIcon},
  threejs:{label:"Three.js",icon:Icons.ThreejsIcon},
  dotnet:{label:".NET",icon:Icons.DotNetIcon},
  framer:{label:"Framer",icon:Icons.FramerIcon},
};

export const TECH_OPTIONS = Object.entries(TECH_MAP).map(([value, { label, icon }]) => ({
  value,
  label,
  icon,
}));
