import type { Metadata } from 'next';
import { Montserrat, Recursive } from 'next/font/google';
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer';
import { Toaster } from '@/components/ui/toaster';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';
import Providers from '@/components/providers';
import './globals.css'
import { TooltipProvider } from '@/components/ui/tooltip';
import { CursorProvider } from '@/providers/cursor-context';

const recursive = Recursive({ subsets: ['latin'] });
export const montserrat = Montserrat({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Code Comfort',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getKindeServerSession();
  const user = session?.getUser ? await session.getUser() : null;
  const isAdmin = user?.email === process.env.ADMIN_EMAIL;
  const userdata = {
    user: user,
    isAdmin: isAdmin,
  }
  return (
    <html lang="en">
      <body className={recursive.className}>
        <Navbar />
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <Providers>
              <CursorProvider>

             
              <TooltipProvider>
              {children}
              </TooltipProvider>
               </CursorProvider>
              </Providers>
          </div>
        </main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
