import type { Metadata } from "next";
import { Montserrat, Recursive } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/common/footer";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/providers/providers";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { CursorProvider } from "@/providers/cursor-context";
import { AuthProvider } from "@/providers/auth-provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { cn } from "@/lib/utils";

const recursive = Recursive({ subsets: ["latin"] });
export const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Code Comfort",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={cn(recursive.className,"bg-[#fff2e2]")}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <Navbar />
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <Providers>
              <CursorProvider>
                <AuthProvider>
                  <TooltipProvider>{children}</TooltipProvider>
                </AuthProvider>
              </CursorProvider>
            </Providers>
          </div>
        </main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
