import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer';
import { Toaster } from '@/components/ui/toaster';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';
import Providers from '@/components/providers';

const inter = Recursive({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getKindeServerSession();
  const user = session?.getUser ? await session.getUser() : null;
  const isAdmin = user?.email === process.env.ADMIN_EMAIL;
  const userdata = {
    user: user,
    isAdmin: isAdmin,
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar userdata={userdata} />
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <Providers>{children}</Providers>
          </div>
        </main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
